### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-html-meta-elements-_f2DoK#1]
@egillespie Can you take a look at this? It's [hosted here](https://normanwi-kapv98gmwdanx_f2dok.surge.sh/) and meets the following criteria:

- [x] Include a homepage and at least one other page, for your best-selling T-shirt (you can download a T-shirt image [from ThinkGeek](http://www.thinkgeek.com/clothing/t-shirts/))
- [x] A language is specified for the website (it does _not_ have to be in English!)
- [x] A `title` and `meta name="description"` are provided for each page
- [x] Every page includes a link to a `favicon.ico` file with the company logo (you can [create one here](https://www.hipsterlogogenerator.com/) or design one yourself)
- [x] Location information is provided on every page (you can place the store anywhere in the world, as long as there's an existing building there)
- [x] When each page is shared on Facebook and Twitter, a beautiful card is generated (and the [respective](https://developers.facebook.com/tools/debug/sharing/) [validators](https://cards-dev.twitter.com/validator) should return no errors/warnings -- though you can ignore the `Share App ID Missing` warning for Facebook)

It's a little bit lower quality than some of my previous websites, but figured I should speed up a lil bit xD
Had fun with the images tho

**Comment by egillespie** [comment]
Haha love it! Thanks for the rick-roll. It's been awhile. Is there a significance to Mt. Saint Helens?

As for the code, most of it is spot on. The Twitter validation passes and it looks like everything is linted. There are a few small issues though:

### No language specified

Your `html` tag is missing the `lang` attribute. Could you add one?

### Use `;` to separate values in `geo.position`

You're using a comma, which is okay for `ICBM`, but not for `geo.position`.

### Use full URL in `meta` tags

Facebook's validator is complaining because your value for `og:url` is `/` instead of a full URL. Can you replace the value with the full URL to make Zuckerberg happy?

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by lordcrekit** [comment]
Was sure I had the lang in there- my bad. Should be good now!

**Comment by egillespie** [comment]
The requested changes look great! It looks like I missed something important on my first pass through your code though:

![image](https://cloud.githubusercontent.com/assets/5572255/23859250/694a573a-07d9-11e7-8cfc-70a25fa801bd.png)

You're using `site` as the content for your `og:type` meta attribute. I think what you intended was [this](http://ogp.me/#type_website).

Sorry I didn't notice this the first time. It should be a straightforward change, but if you have any questions, feel free to send them my way.

After you've updated the code, make sure you no longer get the above warning on Facebook's validator (Twitter is already passing). Then comment back here and I'll review.

Thanks! 🎸

**Comment by lordcrekit** [comment]
I removed og.type completely as it didn't appear to be doing anything.
Added og.description that it was complaining about.
Both pass according to validators (except it still wants a facebook app id ofc)

**Comment by egillespie** [comment]
Looks good! :shipit:
